# Generated by Django 6.0.5 on 2026-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, help_text='teacher full name', max_length=100, null=True, verbose_name='Teacher Name')),
                ('subject', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
