# Generated by Django 6.0.5 on 2026-05-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student854',
            new_name='Student',
        ),
    ]
